spring:
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
    vectorstore:
      pgvector:
        initialize-schema: true
  docker:
    compose:
      lifecycle-management: start_only
logging:
  level:
    org:
      apache:
        pdfbox:
          pdmodel:
            font:
              FileSystemFontProvider: ERROR
server:
  port: 8089